-- =============================================================
-- 송연지 포트폴리오 블로그 — Supabase 스키마 & 데이터 (신규 셋업 전용)
-- ⚠ 이 파일은 "처음 세팅" 또는 "초기화"용입니다. DROP TABLE 이 들어있어
--    이미 운영 중인 DB에 실행하면 전 데이터가 사라집니다.
--    이미 데이터가 있는 DB라면 supabase/migrations/0001_add_sections.sql 을 쓰세요.
-- Supabase Dashboard > SQL Editor 에 붙여넣고 실행.
-- 이 파일이 곧 "API 명세서" 입니다. 컬럼을 바꾸면 프론트도 함께 수정하세요.
-- =============================================================

-- 1) 기존 테이블 제거 (초기화) -------------------------------
DROP TABLE IF EXISTS posts;

-- 2) posts 테이블 생성 --------------------------------------
-- 1행 = 포트폴리오 활동 1건.
-- 프로젝트는 sections(JSONB)에 7섹션 본문을 담는다(메인 카드 그리드 대상).
-- 비프로젝트(자격증/연구실/대외활동/동아리)는 sections를 '{}'로 둔다.
CREATE TABLE posts (
  id            INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT NOT NULL,                 -- 제목
  summary       TEXT NOT NULL,                 -- 한 줄 요약(카드에 노출)
  sections      JSONB NOT NULL DEFAULT '{}'::jsonb, -- 7섹션 본문(객체: intro..skills)
  content       TEXT,                          -- (레거시) 단일 본문. 신규는 sections 사용. 후속 릴리스에서 제거 예정
  activity_date DATE NOT NULL,                 -- 활동 시작 월(정렬/기간 기준)
  end_date      DATE,                          -- 활동 종료 월(진행중/단발성이면 NULL)
  category      TEXT NOT NULL DEFAULT '프로젝트'
                  CHECK (category IN ('프로젝트','자격증','연구실','대외활동','동아리')), -- 분류 5종
  tech_stack    TEXT[] NOT NULL DEFAULT '{}',  -- 기술/키워드 태그
  demo_url      TEXT,                          -- 데모/배포 링크
  repo_url      TEXT,                          -- GitHub 링크
  status        TEXT NOT NULL DEFAULT '완료',   -- 완료 / 진행중
  author        TEXT NOT NULL DEFAULT '송연지',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_posts_activity_date ON posts (activity_date DESC);

-- 3) Row Level Security (RLS) -------------------------------
-- 공개 사이트는 읽기 전용: 익명(anon)에게 SELECT 만 허용.
-- 쓰기 정책은 만들지 않음 → 로컬 dev 미들웨어가 service_role(서버 전용)로만 INSERT.
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read posts"
  ON posts
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- 4) 데이터 ------------------------------------------------
-- 프로젝트 3건: sections(7섹션) 채움. 비프로젝트 5건: sections 기본 '{}'.

-- 4-1) 프로젝트 (메인 카드 그리드에 노출)
INSERT INTO posts (title, summary, sections, activity_date, end_date, category, tech_stack, demo_url, repo_url, status) VALUES
(
  'MySave 북마크 관리 서비스',
  '다시 읽지 않는 북마크 문제를 해결하는 리마인드 기반 서비스',
  jsonb_build_object(
    'intro',    'MySave — 다시 읽지 않는 북마크 문제를 해결하는 리마인드 기반 북마크 관리 서비스.',
    'overview', '저장만 하고 다시 보지 않는 북마크가 쌓이는 문제를 해결하기 위해, 저장·메모·태그·리마인드·웹 대시보드를 제공하는 팀 프로젝트로 기획했습니다.'
  ),
  '2025-12-01', NULL, '프로젝트',
  ARRAY['HTML','CSS','JavaScript','Fetch API','Chrome Extension'],
  NULL, 'https://github.com/MySave1/MySave-Final-Project', '완료'
),
(
  'Tongkk 학습 관리 서비스',
  '요약·퀴즈·통계로 학습 흐름을 관리하는 AI 학습 서비스',
  jsonb_build_object(
    'intro',    'Tongkk — 요약·퀴즈·통계로 학습 흐름을 관리하는 AI 학습 서비스.',
    'overview', '학습 자료를 효율적으로 소화하고 진행 상황을 추적하기 위해, AI 요약·퀴즈 생성·학습 통계를 한 곳에서 제공하는 서비스를 만들었습니다.'
  ),
  '2026-03-01', NULL, '프로젝트',
  ARRAY['TypeScript','React','Vite'],
  NULL, 'https://github.com/yecnz/tongkk', '진행중'
),
(
  'SurfRide 서핑 미니게임',
  'JavaScript 기반 서핑 미니게임 프로젝트',
  jsonb_build_object(
    'intro',    'SurfRide — JavaScript 기반 서핑 테마 웹 미니게임.',
    'overview', '브라우저에서 즐기는 가벼운 미니게임을 목표로, 서핑을 주제로 한 인터랙티브 웹 게임을 제작했습니다.'
  ),
  '2026-06-01', NULL, '프로젝트',
  ARRAY['JavaScript','HTML','CSS','Game UI'],
  NULL, 'https://github.com/hnneul/SurfRide', '완료'
);

-- 4-2) 비프로젝트 (프로필 "경험·활동"에 노출, sections 비움)
-- ⚠ 자격증(SQLD/ADsP)은 src/data/profile.js 고정값으로만 표시 → 중복 방지 위해 DB에는 넣지 않음.
INSERT INTO posts (title, summary, content, activity_date, end_date, category, tech_stack, status) VALUES
(
  '바이오식품소재연구실 인턴',
  '식품 소재 실험과 분석 장비를 경험한 연구실 인턴',
  '소화효소 실험, 패리노그래프, RVA 분석 등을 경험하며 식품 소재의 기능성과 가공 특성을 이해했습니다.',
  '2025-07-01', '2025-09-30', '연구실', '{}', '완료'
),
(
  '멋쟁이사자처럼 프론트엔드',
  '프론트엔드 개발을 배우고 팀 프로젝트를 진행하는 동아리 활동',
  'HTML·CSS·JavaScript와 React를 학습하며 팀 프로젝트를 진행하고 있습니다.',
  '2026-04-01', NULL, '동아리', ARRAY['HTML','CSS','JavaScript','React'], '진행중'
);
